#!/usr/bin/zsh
HISTFILE="${HOME}/.zsh_history"
HISTSIZE=1000000
SAVEHIST=1000000
export TERM=screen-256color
export GOPATH="${HOME}/gopath"
export PATH="${GOPATH}/bin:${HOME}/.cargo/bin:${HOME}/bin:${HOME}/.local/bin:$PATH"
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export EDITOR=nvim
export bastion="azure-az-common-1"
export LANG=en_US.UTF-8
