#!/usr/bin/zsh

alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias vi='vim'
alias highlighter='/home/br/MyTools/highlight-pointer/highlight-pointer -r 5 -o 6'
alias starthttp='python3 -m http.server 9000'
alias devvm='ssh -o ServerAliveInterval=120 -L 0.0.0.0:3128:10.93.12.123:3128 br@10.93.5.55 -D 1080'
alias connsocksproxy='ssh br@10.93.5.55 -D 1080'
alias lr='ls -lrt --color=auto'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias gitlog='git log --graph --pretty=format:"%C(yellow)%h%C(reset) - %C(green)(%ad)%C(reset) %C(bold blue)<%an>%C(reset) %s %C(red)%d%C(reset)" --date=short'
alias gitdiff='git diff --no-ext-diff'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'
