#!/bin/sh

alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias vi='nvim'
alias vim='nvim'
alias highlighter='/home/br/MyTools/highlight-pointer/highlight-pointer -r 5 -o 6'
alias adddns='sudo cp /home/br/Documents/velocix_resolv.conf /etc/resolv.conf'
alias olddevvm='ssh -o ServerAliveInterval=120 -L 3128:10.93.12.123:3128 -L 1339:10.93.12.23:1339 br@10.93.53.31'
alias devvm='ssh -o ServerAliveInterval=120 -L 3128:10.93.12.123:3128 -L 1339:10.93.12.23:1339 br@10.93.5.21'
alias mountdevvm='sshfs br@10.93.5.21:/home/br/ /mnt/devvm'
alias umountdevvm='fusermount3 -u /mnt/devvm'
alias connsocksproxy='ssh br@bastion-chn-in.ext.velocix.com -D 1085'
alias connsitvm='ssh centos@10.93.48.145'
alias k='clear'
alias lr='ls -lrt'
alias rmf='rm -f'
alias gitdiff='git difftool --no-prompt'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias list_systemctl="systemctl list-unit-files --state=enabled"
