#!/bin/sh
HISTFILE="${HOME}/.zsh_history"
HISTSIZE=1000000
SAVEHIST=1000000
export GOPATH="${HOME}/gopath"
export PATH="${HOME}/.cargo/bin":"${GOPATH}/bin":"${HOME}/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export EDITOR=nvim
export bastion="bastion02ch.ext.velocix.com"
export LC_ALL=en_US.UTF-8
