#!/usr/bin/zsh

autoload -Uz vcs_info
autoload -U colors && colors
precmd() { vcs_info }

# Define how unstaged (`%u`) and staged (`%c`) changes are displayed
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' get-untracked true

# Define symbols for different Git states
zstyle ':vcs_info:*' unstagedstr '(✘)'    # Unstaged changes
zstyle ':vcs_info:*' stagedstr '(+)'      # Staged changes
zstyle ':vcs_info:*' untrackedstr '?'     # Untracked files

# Format: Show branch name, and only append status if non-empty
zstyle ':vcs_info:*' formats '%b%u%c'
zstyle ':vcs_info:*' actionformats '%b|%a%u%c'

# Enable prompt substitution
setopt PROMPT_SUBST

PROMPT='%{$fg[cyan]%}%3c%{$fg[yellow]%}${vcs_info_msg_0_:+ $vcs_info_msg_0_} %(?.%{$fg_bold[green]%}❯.%{$fg_bold[red]%}❯%{$fg_bold[red]%}[%?])%{$reset_color%} '
