#!/bin/sh
HISTFILE="${HOME}/.zsh_history"
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export EDITOR=nvim
export bastion="cdn-bastion-velocix"
export PATH="${HOME}/gopath/bin:${PATH}"
export GOPATH="${HOME}/gopath"
